### ISSUE TITLE
OSError: PortAudio library not found

### ISSUE THREAD

**Issue by xavian1996** [qxresearch/qxresearch-event-1#13]
/usr/bin/python3 "/home/unknown/Desktop/Py Script/voice recorder/vr.py"
Traceback (most recent call last):
  File "/home/unknown/Desktop/Py Script/voice recorder/vr.py", line 1, in <module>
    import sounddevice
  File "/var/data/python/lib/python3.8/site-packages/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found

Process finished with exit code 1

**Comment by xiaowuc2** [comment]
Install sounddevice and scipy properly
Please share a screenshot of your error.

**Comment by xavian1996** [comment]
![Screenshot from 2020-10-03 08-41-04](https://user-images.githubusercontent.com/19580407/94986146-39337f00-0554-11eb-93ed-21bf802c2a45.png)

**Comment by TSG405** [comment]
Use this:
>> sudo apt-get install libasound-dev


& reinstall the module —
 >> sudo apt-get install libportaudio2


For other modules :- 

PyAudio 0.2.11 (pip install PyAudio)
                          If there's an error in Package installation, follow :
                          
                                * sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
                                * sudo pip install pyaudio
